/home/inchanbaek/miniconda3/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
[34m[1mwandb[0m: [33mWARNING[0m WandbCallback is deprecated and will be removed in a future release. Please use the WandbMetricsLogger, WandbModelCheckpoint, and WandbEvalCallback callbacks instead. See https://docs.wandb.ai/guides/integrations/keras for more information.
[34m[1mwandb[0m: [33mWARNING[0m The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
Epoch 1/5
Traceback (most recent call last):
  File "/home/inchanbaek/ai_blog/mnist.py", line 27, in <module>
    model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test), callbacks=[wandb_callback])
  File "/home/inchanbaek/miniconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/inchanbaek/miniconda3/lib/python3.12/site-packages/wandb/integration/keras/keras.py", line 668, in on_train_batch_end
    wandb.run.summary["graph"] = wandb.Graph.from_keras(self.model)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inchanbaek/miniconda3/lib/python3.12/site-packages/wandb/sdk/data_types/graph.py", line 357, in from_keras
    for in_layer in _nest(in_node.inbound_layers):
                          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Node' object has no attribute 'inbound_layers'
